[project]
name = "vision-agent"
version = "0.1.0"
description = "Automate anything with a vision agent."
authors = [
    {name = "Maximilian Wessendorf", email = "maximilian.wessendorf@askui.com"},
]
dependencies = [
    "grpcio>=1.67.0",
    "grpcio-tools>=1.67.0",
    "Pillow>=11.0.0",
    "pydantic>=2.9.2",
    "anthropic>=0.37.1",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "UNKNOWN"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
test = [
    "pytest>=8.3.3",
]

[tool.pdm.scripts]
test = "pytest"